version: '3.8'

services:
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6377:6379"

  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static-volume:/vol/static
    ports:
      - "8077:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A Healthy_Care worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A Healthy_Care beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - celery-beat-schedule:/var/celery
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis-data:
  static-volume:
  celery-beat-schedule:
